# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/115f6032-c253-4f21-bf16-aba5db796cdf";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/115f6032-c253-4f21-bf16-aba5db796cdf";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/115f6032-c253-4f21-bf16-aba5db796cdf";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/home/szymon/.local/share/Steam/steamapps" =
    { device = "/dev/disk/by-uuid/115f6032-c253-4f21-bf16-aba5db796cdf";
      fsType = "btrfs";
      options = [ "subvol=@steam" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3B2A-AE3A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/uwu_games" =
    { device = "/dev/disk/by-uuid/e92975bd-e6f1-4528-b045-ebe5157309ab";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/mnt/uwu_backup" =
    { device = "/dev/disk/by-uuid/e92975bd-e6f1-4528-b045-ebe5157309ab";
      fsType = "btrfs";
      options = [ "subvol=@backup" ];
    };

  fileSystems."/mnt/wd_games" =
    { device = "/dev/disk/by-uuid/40e17484-882a-412d-b6e5-741f3de2c2cb";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/mnt/wd_backup" =
    { device = "/dev/disk/by-uuid/40e17484-882a-412d-b6e5-741f3de2c2cb";
      fsType = "btrfs";
      options = [ "subvol=@backup" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
