# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
      "noatime"
    ];
  };

  boot.initrd.luks.devices."cryptroot".device =
    "/dev/disk/by-uuid/1e6e9e2c-e035-4d31-837e-b39087843b03";

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/home/szymon/.local/share/Steam/steamapps" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@steam"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3B2A-AE3A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/wd_backup" = {
    device = "/dev/disk/by-uuid/40e17484-882a-412d-b6e5-741f3de2c2cb";
    fsType = "btrfs";
    options = [
      "subvol=@backup"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/mnt/wd_games" = {
    device = "/dev/disk/by-uuid/40e17484-882a-412d-b6e5-741f3de2c2cb";
    fsType = "btrfs";
    options = [
      "subvol=@games"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/mnt/uwu_games" = {
    device = "/dev/disk/by-uuid/e92975bd-e6f1-4528-b045-ebe5157309ab";
    fsType = "btrfs";
    options = [
      "subvol=@games"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/mnt/uwu_backup" = {
    device = "/dev/disk/by-uuid/e92975bd-e6f1-4528-b045-ebe5157309ab";
    fsType = "btrfs";
    options = [
      "subvol=@backup"
      "compress=zstd"
      "noatime"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
